# Site settings
title: Hack for Houston
description: >- 
  Hack For Houston is a club created to provide a framework to connect 
  the computer science talent at Rice University with nonprofits in the 
  greater Houston area.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/hfhsite/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://samanyougarg.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: hackforhouston
twitter: twitter
github:  kyranstar/hfhsite

#Additional Pages
about: about
blog: blog
leadership: leadership
signup: signup
contact: contact


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: kyranstar #github username
repo: hfhsitelive #github repository
branch: master #branch
relative_source: _site #source directory
destination: _site #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml